# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools
x = int(input("size: "))
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix
#Example of using permutations() method
t = list(itertools.permutations('1234567890', x))
A = random_matrix(x)
print(A)
i = 1
j = 1
def minor(A, i, j):
    """
    find minor
    """
    for i in range(len(A) - 1):
        for j in range(len(A) - 1):
            if len(A[i]) > len(A[j]):
                del A[j]
            elif len(A[i]) < len(A[j]):
                del A[i]
def det_recursive(A):
    """
    funchion use numpy for colculated det matrix(A)
    """
    sol = 0
    if A.shape != (1, 1):
        for i in range(A.shape[0]):
            sol = sol + (-1) ** i * A[i, 0] * det_recursive(np.delete(np.delete(A, 0, axis=1), i, axis=0))
        return sol
    else:
        return A[0, 0]
print(det_recursive(A))
print(np.linalg.det(A))

[[8 1 8 5]
 [3 3 8 1]
 [8 3 7 6]
 [4 0 0 6]]
-230
-229.99999999999983
